version: 2

sources:
  - name: staging
    schema: STAGING
    tables:
      - name: STG_ES_AESOP_REF_WASTE_TYPE
        description: "This table contains reference data for waste types used in the AESOP system."
