version: 2

models:
  - name: ODS_ES_BYOD_PROJ_HOUR_COST_PRICE
    tests:
      - check_columns_not_null
    meta:
      column_list:
        - DEFINITIONGROUP
        - EXECUTIONID
        - ISSELECTED
        - TRANSFERSTATUS
        - CATEGORYID
        - COSTPRICE
        - EFFECTIVELABORRATE
        - ISRESOURCERATE
        - PROJECTID
        - CUSTOMERACCOUNT
        - PRICEGROUPID
        - PROJECTCONTRACTID
        - RESOURCECATEGORY
        - TRANSDATE
        - RESOURCEID
        - RESOURCECATEGORYID
        - RESOURCECOMPANYID
        - PARTITION
        - DATAAREAID
        - SYNCSTARTDATETIME
        - RECID
        - SF_INSERT_TIMESTAMP
