version: 2

sources:
  - name: demo
    database: dbt_source
    schema: public
    tables:
      - name: customers
        columns:
          - name: customer_name
            tests:
              - unique
              - not_null
      - name: orders
