WITH source_data AS (
  SELECT *
  FROM {{ ref('ODS_ES_BYOD_PROJ_HOUR_COST_PRICE') }}
)

SELECT *
FROM source_data
WHERE {{ check_null_columns([
  'DEFINITIONGROUP', 'EXECUTIONID', 'ISSELECTED', 'TRANSFERSTATUS', 'CATEGORYID',
  'COSTPRICE', 'EFFECTIVELABORRATE', 'ISRESOURCERATE', 'PROJECTID', 'CUSTOMERACCOUNT',
  'PRICEGROUPID', 'PROJECTCONTRACTID', 'RESOURCECATEGORY', 'TRANSDATE', 'RESOURCEID',
  'RESOURCECATEGORYID', 'RESOURCECOMPANYID', 'PARTITION', 'DATAAREAID', 'SYNCSTARTDATETIME',
  'RECID', 'SF_INSERT_TIMESTAMP'
]) }}